workflows:
  ios-release-workflow:
    name: Pump Alignment iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest # <-- 'stable' ko hatakar 'latest' kiya jo exact version detect karega
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Initialize and Fetch Dependencies
        script: |
          flutter pub get

      - name: Build iOS App Bundle
        script: |
          # Code compilation without Apple Developer account signing
          flutter build ios --release --no-codesign

      - name: Packaging .app to .ipa Custom Payload
        script: |
          # Sideload wrapper bundle creation sequence
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r pump_alignment.ipa Payload
    artifacts:
      - "*.ipa"