workflows:
  ios-release-workflow:
    name: Pump Alignment iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: stable
    triggering:
      events:
        - push
      watched_branches:
        - master
    scripts:
      - name: Initialize and Fetch Dependencies
        script: |
          flutter pub get

      - name: Build iOS App Bundle
        script: |
          # Without Apple Developer Account signing, --no-codesign flag is required
          flutter build ios --release --no-codesign

      - name: Packaging .app to .ipa Custom Payload
        script: |
          # Packaging into a zip payload for easy sideloading
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r pump_alignment.ipa Payload
    artifacts:
      - "*.ipa"